SHELL :=/bin/bash

install: iframeResizer clipboardjs

iframeResizer:
	cp -uv node_modules/iframe-resizer/js/iframeResizer.* js/

clipboardjs:
	cp -uv node_modules/clipboard.js/dist/clipboard.min.js js/
